### ISSUE TITLE
SEO --Google Description

### ISSUE THREAD

**Issue by raulromero1** [Yakera-org/website-bug-reports#12]
Add description "Yakera is a crowdfunding platform that changes how humanitarian aid is delivered around the world. We leverage the power of storytelling to build global solidarity and accelerate international development." for display in search engines

<img width="734" alt="Screen Shot 2021-09-30 at 11 01 19 AM" src="https://user-images.githubusercontent.com/91638232/135480653-c23eebb3-823d-4970-87f0-841b2c88a49d.png">

**Comment by BravoAndres** [comment]
Fixed.
