### ISSUE TITLE
Donor Success Email Prompted (even when donations were not completed)

### ISSUE THREAD

**Issue by raulromero1** [Yakera-org/website-bug-reports#14]
![WhatsApp Image 2021-10-03 at 6 24 22 PM](https://user-images.githubusercontent.com/91638232/135774077-8ecf86b8-e9cb-49af-a607-ee329a408da6.jpeg)

This email was prompted even when the donation was not completed and it's not optimized for mobile either!

**Comment by BravoAndres** [comment]
@andresdst

**Comment by BravoAndres** [comment]
Solved.
