### ISSUE TITLE
Donate button turns white when hovered over

### ISSUE THREAD

**Issue by raulromero1** [Yakera-org/website-bug-reports#17]
Donate button disappears when hovered over, which could cause users to interrupt their journey or become confused as to where they need to click to donate

<img width="1440" alt="Screen Shot 2021-10-05 at 9 47 47 AM" src="https://user-images.githubusercontent.com/91638232/136036386-87184fdb-e0d1-48fb-bb80-4242c9cd5cb6.png">
<img width="1440" alt="Screen Shot 2021-10-05 at 9 47 50 AM" src="https://user-images.githubusercontent.com/91638232/136036391-2d2d73bc-2eeb-4943-aea4-03d8b45df50e.png">

**Comment by BravoAndres** [comment]
Solved. Changes will be live on the page in the next release.
