### ISSUE TITLE
Small Business category in the homepage doesn't have a name associated with it

### ISSUE THREAD

**Issue by raulromero1** [Yakera-org/website-bug-reports#19]
<img width="1440" alt="Screen Shot 2021-10-05 at 4 45 42 PM" src="https://user-images.githubusercontent.com/91638232/136100157-e28f3bf5-c031-47ac-bbfe-28fa263f159c.png">

**Comment by BravoAndres** [comment]
Solved. Changes will be live on the page in the next release.
