### ISSUE TITLE
Icon disappears when selecting more info in homepage

### ISSUE THREAD

**Issue by raulromero1** [Yakera-org/website-bug-reports#20]
<img width="1440" alt="Screen Shot 2021-10-07 at 5 21 39 PM" src="https://user-images.githubusercontent.com/91638232/136464630-656fdded-5157-4501-8186-ed6c19a95445.png">
<img width="1440" alt="Screen Shot 2021-10-07 at 5 21 42 PM" src="https://user-images.githubusercontent.com/91638232/136464631-abc76a17-4dee-4d58-a8e9-e08ffde1f637.png">

**Comment by BravoAndres** [comment]
Solved. Changes will be live on the page in the next release.
