### ISSUE TITLE
Change AirTM field to not required 

### ISSUE THREAD

**Issue by BravoAndres** [Yakera-org/website-bug-reports#22]
Even though Airtm field is not required, it still says '**this field can not be empty** '

<img width="884" alt="Screen_Shot_2021-10-11_at_11 39 08_AM" src="https://user-images.githubusercontent.com/68721629/136823120-d3720568-8931-4100-9ad4-467dae240405.png">

**Comment by jango707** [comment]
Resolved a while ago
