### ISSUE TITLE
Campaign submission error

### ISSUE THREAD

**Issue by raulromero1** [Yakera-org/website-bug-reports#25]
Although we limit the amount of files and pictures to 5, we do not tell recipients about this, prompting errors when they are creating campaigns that they cannot identify.

Suggestion: lift amount of files & pics to 7 and modify error message to say it's max 7

![Bug yakera](https://user-images.githubusercontent.com/91638232/137916263-6be1b3b3-f86f-4a44-b0ef-3e85406abd85.jpg)

**Comment by jango707** [comment]
Resolved a while ago
