### ISSUE TITLE
Typo in About us

### ISSUE THREAD

**Issue by raulromero1** [Yakera-org/website-bug-reports#27]
Replace "Diretly" with "Directly"
<img width="423" alt="Screen Shot 2021-10-23 at 9 11 45 PM" src="https://user-images.githubusercontent.com/91638232/138576226-9c1f12f3-abc7-4487-9f6e-99e8f0fc2ab2.png">

**Comment by BravoAndres** [comment]
Solved. Changes will be live on the page in the next release.
