### ISSUE TITLE
Homepage campaigns (fix)

### ISSUE THREAD

**Issue by raulromero1** [Yakera-org/website-bug-reports#29]
1. Showing too many campaigns in the homepage and not giving users the capacity to learn more or visit more campaigns
2. Cards are undersized (reduce to 3)
3. Campaign pictures all have different sizes
4. No see more click!
5. All campaigns are featured rather than the 6 more successful
<img width="1432" alt="Screen Shot 2021-11-14 at 8 00 21 PM" src="https://user-images.githubusercontent.com/91638232/141706798-102e8040-750e-46c4-93b7-8d6f89df8015.png">

**Comment by jango707** [comment]
Duplicate
