### ISSUE TITLE
Update Thank You Card

### ISSUE THREAD

**Issue by raulromero1** [Yakera-org/website-bug-reports#33]
Update thank you card so it moves from the old formatting to the new brand identity. By having a homogenous brand identity throughout our journey, we will increase the trust in the platform and improve engagement, especially if we incorporate CTAs into our post-transaction messaging.

<img width="1439" alt="Screen Shot 2021-11-22 at 8 33 56 AM" src="https://user-images.githubusercontent.com/91638232/142951116-f158b65f-5cf0-4e9d-93a2-4d2c1f6e6444.png">

Mariana has provided the design assets here

![donationcard-yakera](https://user-images.githubusercontent.com/91638232/142951185-a0ae5125-3e8d-4965-9b32-bc67dbae92d8.png)

 https://drive.google.com/drive/folders/1BL1YQWzwV5hHFVyW4P_V_-tl3cugDUn_

In addition, we need to also fix the donation amount that we are showing. Rather than the whole-donation amount that includes the tip, we should show just the donation to the campaign portion. If a user then returns to the campaign to see their donation, then they will not be able to see the full amount mentioned in the donation card and there's a discrepancy between both things

**Comment by jango707** [comment]
Done recently
