### ISSUE TITLE
Changing campaign display on the homepage to 8 most successful campaigns with a "view more" option

### ISSUE THREAD

**Issue by raulromero1** [Yakera-org/website-bug-reports#35]
Currently, we display all campaigns on the homepage but we do not lead users to check them all out and see more and we often show campaigns that have $0 in support on the homepage. 

We need to run a search that shows the 8 most successful campaigns based on % of the total amount and reduce the amount displayed per-screen from 5 to 4. We also need to enable a "view more" button that leads users to the campaigns page because at the moment we only take them to the specific campaigns but not the campaigns page itself. 

<img width="1439" alt="Screen Shot 2021-11-22 at 9 52 29 AM" src="https://user-images.githubusercontent.com/91638232/142951541-c5c8e414-d009-44ba-957e-dee53aa668bb.png">

**Comment by jango707** [comment]
Duplicate
