### ISSUE TITLE
Mweb Campaigns - 404 Issue in Venezuela

### ISSUE THREAD

**Issue by raulromero1** [Yakera-org/website-bug-reports#38]
Whenever a user opens the campaigns tab in their mobile browser, they see a 404 error. Reported by Mariana

<img width="318" alt="Screen Shot 2021-11-27 at 10 11 22 AM" src="https://user-images.githubusercontent.com/91638232/143686881-d4f44e44-d232-45de-8cf2-8da0c4b943d8.png">

**Comment by jango707** [comment]
Fixed
