### ISSUE TITLE
Donation Success Error

### ISSUE THREAD

**Issue by raulromero1** [Yakera-org/website-bug-reports#7]
I decided to donate $5 to the campaign and give $3 to the platform as a tip. However, instead of showing "Thank you for donating $8" after my donation was successfully submitted, it said "thank you for donating $53" I suspect that instead of adding 5 + 3, it put them as two digits. 
<img width="1440" alt="Screen Shot 2021-09-29 at 6 40 35 PM" src="https://user-images.githubusercontent.com/91638232/135358845-ab5e1903-1f6a-41ec-a765-9e5ff33657f0.png">

**Comment by jango707** [comment]
Fixed with latest commit
