### ISSUE TITLE
Paypal Loading Bar -- Still Present After Loading

### ISSUE THREAD

**Issue by raulromero1** [Yakera-org/website-bug-reports#8]
Instead of disappearing after the card field has opened, the loading bar kept appearing and moving while I was filling out my card details.
<img width="1440" alt="Screen Shot 2021-09-29 at 6 39 55 PM" src="https://user-images.githubusercontent.com/91638232/135358989-7e2cb015-a5e8-4d4b-8af4-5e0137a5cea8.png">

**Comment by jango707** [comment]
Fixed with latest commit
