### ISSUE TITLE
No Thumbnail in Twitter

### ISSUE THREAD

**Issue by raulromero1** [Yakera-org/website-bug-reports#9]
Whenever I tweet, the thumbnail is not shown. We must optimize the thumbnail for twitter so that it happens automatically. 

<img width="1440" alt="Screen Shot 2021-09-30 at 8 40 05 AM" src="https://user-images.githubusercontent.com/91638232/135456658-ead27261-e9a0-4725-a53c-748de99d0c66.png">

**Comment by jango707** [comment]
tested this, and seems to be resolved
